### ISSUE TITLE
Remove joke references

### ISSUE THREAD

**Issue by chippytech** [WybeNetwork/VistaPanel-Demo#5]
Can you remove jokes, typos, etc. like "Michaelsoft Binbows", "owo.ini", "no wifi LOL", "Binbows NT 10.0", "Everything is Disbaled because its just a vPanel Demo ok?" and more.

**Comment by zeroninefourfour** [comment]
Ok,
 _Goodbye,Michaelsoft
    MeTooIDK -2022_

**Comment by 4yx** [comment]
The final traces seem to be eliminated in #8.

> Goodbye,Michaelsoft

This was a tragic day.

**Comment by ghost** [comment]
> The final traces seem to be eliminated in #8.

There's still hidden traces, like a rickroll I found and removed on 9478ba5.
